name: plantopia
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dash_chat_2: ^0.0.20
  chat_gpt_sdk: ^3.0.8
  blur: ^4.0.0
  flutter_markdown: 0.7.2
  cupertino_icons: ^1.0.6
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  dio: ^5.4.3+1
  intl: 0.19.0
  geolocator: ^11.0.0
  flutter_svg: ^2.0.10+1
  country_code_picker: ^3.0.0
  shared_preferences: ^2.2.3
  syncfusion_flutter_gauges: ^25.2.6
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  flutter_otp_text_field: ^1.1.3+2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_time_picker_spinner: ^2.0.0
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  html: ^0.15.4
  flutter_widget_from_html_core: ^0.15.1
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/vectors/
    - .env
    - assets/icons/
    - assets/onboarding/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
